### PR TITLE
[#767] Rework `crucible.methods.generateId` and `SYSTEM.EFFECTS.getEffectId`, fix misc bugs

### LINKED ISSUE #767: Miscellaneous 0.9.1 bugfixes
- Hamstring throws an error if using a two-handed weapon
- Vampiric Bite does not account for natural weapons training
- Armored Shell throws an error if using a two-handed weapon
- Adrenaline Surge does not recognize the effect
- Vow of Animus does not recognize the effect

### PR DESCRIPTION
**Pull request by roth-michael**
Closes #767 
For Hamstring & Armored Shell, optional chain for offhand. For Vampiric Bite, call `prepareEquippedData` on the data model of the synthetic weapon. For Adrenaline Surge & Vow of Animus, rework `generateId` and `getEffectId`:
- `generateId` now preserves casing
- `getEffectId` now calls `generateId`
- `getEffectId` now accepts an optional `suffix` which replaces the last `n` characters of the returned string with `suffix` (where `n` is the length of `suffix`)
- `getEffectId` with the `suffix` argument is now used when assigning effect `_id`s in `CrucibleAction##attachOutcomeEffects`

I would be down to rename `generateId` to `slugify`, and potentially move `getEffectId` into `crucible.api.methods`, and rename it to `generateId`.

### CODE REVIEW

File: module/const/effects.mjs [hunk 1]
```diff
@@ -10,10 +10,11 @@
 /**
  * Get a standardized 16 character ID that can be used for the ActiveEffect.
  * @param {string} label    The active effect label
+ * @param {string} [suffix] A suffix with which to end the returned ID
  * @returns {string}        The standardized ID
  */
-export function getEffectId(label) {
-  return label.slugify({replacement: "", lowercase: false, strict: true}).slice(0, 16).padEnd(16, "0");
+export function getEffectId(label, suffix="") {
```
Comment (aaclayton) [inline module/const/effects.mjs]: I'd prefer we use an `options` object, never know when we might need another option and it sucks to have to extend or break the method signature every time.

**Review by aaclayton — CHANGES_REQUESTED** [review]

**Review by aaclayton — APPROVED** [review]
