### PR TITLE
[#743] Fix missing weapon choice for some offhand scenarios, re-add weapon context tags to action use dialog

### LINKED ISSUE #743: Having nothing (unarmed) or a shield in offhand breaks non-mainhand-tagged strikes
https://discord.com/channels/170995199584108546/1116696333894570094/1482481483796054138
`strike`, unless otherwise tagged, defaults to lowest-cost, and weapon choice is not allowed for offhand unarmed or shields.

### PR DESCRIPTION
**Pull request by roth-michael**
Closes #743 

Changes:
- `weapons.hasChoice` is now only not true if no natural weapons and a two-handed weapon is wielded
- If `strict` not passed to `getValidWeaponChoices`, all possible weapons are returned (besides natural - maybe we could change that), but with `isValid: false`. This lets us properly select a default weapon, for instance, in the `strike` tag's `prepare` hook
- Re-added context tags to show what weapon is being used for a `strike` (I think maybe these got accidentally lost)

### CODE REVIEW

File: module/models/action.mjs [hunk 1]
```diff
@@ -1374,31 +1374,43 @@ export default class CrucibleAction extends foundry.abstract.DataModel {
...
+   * @returns {{item: CrucibleWeaponItem, label: string, id: string, isValid: boolean}[]}
    */
   getValidWeaponChoices({strict=false, maxCost=null}={}) {
     const choices = [];
     if ( !["strike", "reload"].some(t => this.tags.has(t)) ) return choices;
     const {mainhand: mh, offhand: oh, natural} = this.actor.equipment.weapons;
     const isValidChoice = weapon => {
       if ( this.tags.has("reload") ) return weapon.system.needsReload;
-      let isValid = this.tags.has("ranged") && weapon.config.category.ranged && !(strict && weapon.system.needsReload);
+      let isValid = this.tags.has("ranged") && weapon.config.category.ranged && !weapon.system.needsReload;
```
Comment (aaclayton) [inline module/models/action.mjs:1387]: Why do we remove the `strict` check here when determining whether weapon loaded state is valid or not?

File: module/models/action.mjs [hunk 2]
```diff
@@ -1374,31 +1374,43 @@ export default class CrucibleAction extends foundry.abstract.DataModel {
...
+        item: oh,
+        id: oh.id || "offhandUnarmed",
+        label: `${oh.name} (${SYSTEM.WEAPON.SLOTS.labels.OFFHAND})`,
+        isValid
+      });
     }
     if ( !this.tags.has("ranged") ) {
       for ( const n of natural ) {
-        choices.push({item: n, id: n.id, label: `${n.name} (${SYSTEM.WEAPON.PROPERTIES.natural.label})`});
+        choices.push({item: n, id: n.id, label: `${n.name} (${SYSTEM.WEAPON.PROPERTIES.natural.label})`, isValid: true});
```
Comment (aaclayton) [inline module/models/action.mjs]: We skip the `maxCost` check here that we make for other weapons. That seems undesirable. I would imagine that affordability would rule out natural weapons in `strict` mode.

File: module/models/actor-base.mjs [hunk 3]
```diff
@@ -676,7 +676,7 @@ export default class CrucibleBaseActor extends foundry.abstract.TypeDataModel {
     weapons.dualWield = weapons.unarmed || (mh?.id && oh?.id && !weapons.shield);
     weapons.dualMelee = weapons.dualWield && !mhCategory.ranged && !ohCategory.ranged;
     weapons.dualRanged = weapons.dualWield && mhCategory.ranged && ohCategory.ranged;
-    weapons.hasChoice = weapons.dualWield || (weapons.natural.length > 0) || (weapons.melee && weapons.ranged);
+    weapons.hasChoice = (weapons.natural.length > 0) || !weapons.twoHanded;
```
Comment (aaclayton) [inline module/models/actor-base.mjs:679]: Confirming my understanding that this will result in a choice for an actor with a 1h weapon equipped and no offhand (or an offhand only and no mainhand) where they can choose their unarmed strike?

File: module/const/action.mjs [hunk 4]
```diff
@@ -600,9 +600,13 @@ export const TAGS = {
...
-        const valid = this.getValidWeaponChoices();
-        valid.sort((a, b) => a.item.system.actionCost - b.item.system.actionCost);
-        this.usage.weapon = valid[0]?.item;
+        const valid = this.getValidWeaponChoices({maxCost: this.actor.resources.action.value});
+        for ( const weapon of valid ) {
+          if ( !weapon.isValid ) continue;
+          this.usage.weapon = weapon.item;
+          break;
+        }
+        this.usage.weapon ??= valid[0]?.item;
```
Comment (aaclayton) [inline module/const/action.mjs:611]: Previously the fallback weapon was sorted as the cheapest one. Confirming that it's intentional that we choose `valid[0]` in declaration order? Might be worth a comment.

File: module/models/action.mjs [hunk 5]
```diff
@@ -1374,31 +1374,43 @@ export default class CrucibleAction extends foundry.abstract.DataModel {
...
   getValidWeaponChoices({strict=false, maxCost=null}={}) {
     const choices = [];
     if ( !["strike", "reload"].some(t => this.tags.has(t)) ) return choices;
     const {mainhand: mh, offhand: oh, natural} = this.actor.equipment.weapons;
     const isValidChoice = weapon => {
       if ( this.tags.has("reload") ) return weapon.system.needsReload;
-      let isValid = this.tags.has("ranged") && weapon.config.category.ranged && !(strict && weapon.system.needsReload);
+      let isValid = this.tags.has("ranged") && weapon.config.category.ranged && !weapon.system.needsReload;
       isValid ||= this.tags.has("melee") && !weapon.config.category.ranged;
       if ( maxCost !== null ) isValid &&= weapon.system.actionCost <= maxCost;
```
Comment (aaclayton) [inline module/models/action.mjs]:
```suggestion
      if ( maxCost !== null ) isValid &&= (weapon.system.actionCost <= maxCost);
```

**Review by aaclayton — CHANGES_REQUESTED** [review]
Looks good! A few callouts and minor tweaks before merging

File: module/models/action.mjs (hunk 1 above)
Comment (roth-michael) [reply module/models/action.mjs:1387]: We changed `strict` to mean "should invalid items be filtered out, or simply returned with `isValid: false`, so it no longer made sense to have that inside this `isValidChoice` function.

File: module/models/actor-base.mjs (hunk 3 above)
Comment (roth-michael) [reply module/models/actor-base.mjs:679]: Correct. Will also allow someone with mainhand and offhand _shield_ to smack with shield, if desired.

File: module/const/action.mjs (hunk 4 above)
Comment (roth-michael) [reply module/const/action.mjs:611]: Confirmed intentional - until/unless we implement some `lastStrike` which tracks what the last weapon used for a strike was, we should always prefer mainhand over offhand, as the alternative would be (for a one-handed, nothing-in-offhand actor) an always-cheaper cost of the offhand unarmed strike, which isn't great UX. I'll add a comment.

**Review by aaclayton — APPROVED** [review]
